### PR TITLE
Add circle ci config

### PR DESCRIPTION
**Pull request by ConnorChristie**

### CODE REVIEW

**Comment by mgwelch** [comment]
Why the switch to circle?

**Comment by ConnorChristie** [comment]
They have artifact hosting support which we can use to host our previews and postman collections

You can go to one of the builds and view the artifacts then click on the index.html file to see the preview!

**Comment by mgwelch** [comment]
Nevermind I see you are using circle ci for the other project

**Comment by ConnorChristie** [comment]
@mgwelch Good to go. The other circle build seems to be failing because it can't find the config in master yet

**Comment by mgwelch** [comment]
I'll write I'll give it a go.

**Comment by mgwelch** [comment]
Looks like i have to temporarily turn off required checks.

**Pull request merged**
